name: junaediakbar_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: 4.6.5
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^1.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/img/
  uses-material-design: true
